/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examination_management_system;


import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.*;
/**
 *
 * @author majma
 */
public class AddQuestion extends javax.swing.JFrame {

    /**
     * Creates new form AddQuestion
     */
    String selEx, curn;
    public AddQuestion() {
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        qid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        op2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        op3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        op4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        exam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        qstn = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        op1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Question");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Select Exam");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 210, 20));

        qid.setEditable(false);
        getContentPane().add(qid, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 200, 40));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("Enter the question");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 30));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("Option B");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 20));
        getContentPane().add(op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 270, 40));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setText("Option C");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 20));
        getContentPane().add(op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 270, 40));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Option D");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 100, 20));
        getContentPane().add(op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 270, 40));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setText("Answer");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 370, 100, 20));
        getContentPane().add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 270, 40));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("Question ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 210, 20));

        exam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                examItemStateChanged(evt);
            }
        });
        exam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                examFocusLost(evt);
            }
        });
        exam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                examMouseExited(evt);
            }
        });
        exam.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                examInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        exam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examActionPerformed(evt);
            }
        });
        getContentPane().add(exam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 240, 40));

        qstn.setColumns(20);
        qstn.setRows(5);
        jScrollPane1.setViewportView(qstn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 560, 130));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 150, 50));

        jButton2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 150, 50));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setText("Option A");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 20));
        getContentPane().add(op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String ques, opt1, opt2, opt3, opt4, qstnid, selexam, answer;
        ques = qstn.getText();
        opt1 = op1.getText();
        opt2 = op2.getText();
        opt3 = op3.getText();
        opt4 = op4.getText();
        qstnid = qid.getText();
        selexam = exam.getSelectedItem().toString();
        answer = ans.getText();
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ems","root","");
            Statement st=con.createStatement();
           
            st.executeUpdate("insert into question values('"+qstnid+"','"+selexam+"','"+ques+"','"+opt1+"','"+opt2+"','"+opt3+"','"+opt4+"','"+answer+"')");
            JOptionPane.showMessageDialog(this, "Question added successfully!");
            op1.setText("");
            op2.setText("");
            op3.setText("");
            op4.setText("");
            ans.setText("");
            qstn.setText("");
            String qsid;
            int num = Character.getNumericValue(qstnid.charAt(6))*10+Character.getNumericValue(qstnid.charAt(7));
            num += 1;
            if(num < 10) qsid = "0"+String.valueOf(num);else qsid = String.valueOf(num); 
            qid.setText(selEx+qsid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ans, "Question can't added!", "Error", 2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ems","root","");
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select eid from exam");
            while(rs.next()){
                exam.addItem(rs.getString("eid"));
            }
            con.close();
            
        } catch (Exception e) {
            System.err.println(e);
        }
        ;
    }//GEN-LAST:event_formWindowOpened

    private void examMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_examMouseClicked

    private void examMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_examMouseExited

    private void examInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_examInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_examInputMethodTextChanged

    private void examItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_examItemStateChanged
        // TODO add your handling code here:
//        selEx = exam.getSelectedItem().toString().toUpperCase();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yy");  
        LocalDateTime now = LocalDateTime.now();  
        String res="";
        String qsid="", qstn="";
        String arr[];
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ems","root","");
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select ename from exam where eid='"+exam.getSelectedItem().toString()+"'");
            rs.next();
            selEx = rs.getString("ename").toUpperCase();
            arr = selEx.split(" ");
            selEx = String.valueOf(arr[0].charAt(0))+String.valueOf(arr[0].charAt(1))+String.valueOf(arr[1].charAt(0))+String.valueOf(arr[1].charAt(1))+dtf.format(now);
            
            rs = st.executeQuery("select count(*) from question where exam = '"+exam.getSelectedItem().toString()+"'");
            rs.next();

            if(Integer.parseInt(rs.getString("count(*)"))>0){
                rs = st.executeQuery("select qid from question where exam = '"+exam.getSelectedItem().toString()+"'");
                while(rs.next()){
                res = rs.getString("qid");
            }
            
            int num;
            try {
                num = Character.getNumericValue(res.charAt(6))*10+Character.getNumericValue(res.charAt(7));
                num += 1;
                if(num < 10) qsid = "0"+String.valueOf(num);else qsid = String.valueOf(num);
                qsid = selEx + qsid;
    
            } catch (Exception e) {
                System.err.println(e);
            }
                
            }else{
                qsid = selEx+"01";
            }
            qid.setText(qsid);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(ans, "Exam name must contains two words", "Exam Name Error", 1);
        }
        
        
        
    }//GEN-LAST:event_examItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        op1.setText("");
        op2.setText("");
        op3.setText("");
        op4.setText("");
        ans.setText("");
        qstn.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void examFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_examFocusLost
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_examFocusLost

    private void examActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JComboBox<String> exam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField op1;
    private javax.swing.JTextField op2;
    private javax.swing.JTextField op3;
    private javax.swing.JTextField op4;
    private javax.swing.JTextField qid;
    private javax.swing.JTextArea qstn;
    // End of variables declaration//GEN-END:variables
}
