/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examination_management_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author majma
 */
public class ExamPortal extends javax.swing.JFrame {

    /**
     * Creates new form ExamPortal
     */
    static String name = "Muhammed Ajmal", userid = "180021030987";
    String[][] ques = new String[100][10];
    String[] ansstr = new String[100];
    String eid="COSC21";
    int initCounter = 0;
    int nc=0, pc=0;
    JButton[] obj;
    JRadioButton[] jr = new JRadioButton[10];
    public void string(String str, String user, String examid){
        name = str;
        userid = user;
        eid = examid;
    }
    
    public ExamPortal() {
        initComponents();
        bgrp.add(op1);
        bgrp.add(op2);
        bgrp.add(op3);
        bgrp.add(op4);
        obj = new JButton[]{q1,q2,q3,q4,q5,q6,q7,q8,q9,q10};
        ps.setEnabled(false);
        for(int i=0;i<10;i++)
            ansstr[i] = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrp = new javax.swing.ButtonGroup();
        timers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        op2 = new javax.swing.JRadioButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        op1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        q2 = new javax.swing.JButton();
        q3 = new javax.swing.JButton();
        q1 = new javax.swing.JButton();
        q4 = new javax.swing.JButton();
        q5 = new javax.swing.JButton();
        q6 = new javax.swing.JButton();
        q7 = new javax.swing.JButton();
        q8 = new javax.swing.JButton();
        q10 = new javax.swing.JButton();
        q9 = new javax.swing.JButton();
        nt = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        ps = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        qnum = new javax.swing.JLabel();
        prevans = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Examination Portal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timers.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        timers.setText("00:00:00");
        getContentPane().add(timers, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 140, 40));

        question.setEditable(false);
        question.setColumns(20);
        question.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        question.setRows(5);
        question.setText("Question");
        question.setWrapStyleWord(true);
        jScrollPane1.setViewportView(question);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 510, 170));

        op2.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        op2.setText("Option B");
        op2.setContentAreaFilled(false);
        getContentPane().add(op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 470, 30));

        op3.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        op3.setText("Option C");
        op3.setContentAreaFilled(false);
        getContentPane().add(op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 470, 30));

        op4.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        op4.setText("Option D");
        op4.setContentAreaFilled(false);
        getContentPane().add(op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 480, 30));

        op1.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        op1.setText("Option A");
        op1.setContentAreaFilled(false);
        getContentPane().add(op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 470, 30));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        q2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q2.setText("2");
        jPanel1.add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 70, 40));

        q3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q3.setText("3");
        jPanel1.add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 70, 40));

        q1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q1.setText("1");
        jPanel1.add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 70, 40));

        q4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q4.setText("4");
        jPanel1.add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, 40));

        q5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q5.setText("5");
        jPanel1.add(q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 40));

        q6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q6.setText("6");
        jPanel1.add(q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 70, 40));

        q7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q7.setText("7");
        jPanel1.add(q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 70, 40));

        q8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q8.setText("8");
        jPanel1.add(q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 70, 40));

        q10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q10.setText("10");
        jPanel1.add(q10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 215, 70, 40));

        q9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        q9.setText("9");
        jPanel1.add(q9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 350, 280));

        nt.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        nt.setText("Next");
        nt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntActionPerformed(evt);
            }
        });
        getContentPane().add(nt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 100, 60));

        submit.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        submit.setText("Submit");
        submit.setPreferredSize(new java.awt.Dimension(100, 60));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, 60));

        ps.setFont(new java.awt.Font("Georgia", 1, 13)); // NOI18N
        ps.setText("Previous");
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 60));

        userName.setBackground(new java.awt.Color(153, 153, 153));
        userName.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userName.setText("Welcome User");
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 330, 40));

        qnum.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        qnum.setText("Question No. 1");
        getContentPane().add(qnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 24, 220, 40));

        prevans.setEditable(false);
        prevans.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        getContentPane().add(prevans, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 330, 40));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("Previous Answer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Projectleader2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        //Timer
        
        new Thread() {
            public void run() {
                int min=0, sec=0;
                String mn="",sc="";
                try {
                    while(true){
                        sec++;
                        if(sec == 60){
                            sec = 0;
                            min++;
                            if(min == 10)
                                break;
                        }
                        if(sec<10)sc="0"+sec;
                        else sc=sec+"";
                        if(min<10)mn="0"+min;
                        else mn=min+"";
                        timers.setText("00:"+mn+":"+sc);
                        Thread.sleep(1000);
                        
                    }
                    timers.setText("00:10:00");
                    if(min == 10){
                        submit.setEnabled(true);
                        submit.doClick();
                    }
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }.start();
        
        
        submit.setEnabled(false);
        userName.setText(name);
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/ems","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from question where exam='"+eid+"'");
            int counter = 0;
            while(rs.next()){
                ques[counter][0] = rs.getString("qstn");
                ques[counter][1] = rs.getString("op1");
                ques[counter][2] = rs.getString("op2");
                ques[counter][3] = rs.getString("op3");
                ques[counter][4] = rs.getString("op4");
                ques[counter][5] = rs.getString("ans");
                counter++;
            }
            question.setText(ques[0][0]);
            qnum.setText("Question No.: "+(initCounter+1));
            op1.setText(ques[0][1]);
            op2.setText(ques[0][2]);
            op3.setText(ques[0][3]);
            op4.setText(ques[0][4]);
            
            initCounter++;
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_formWindowOpened
    int tc = -1;
    private void ntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntActionPerformed
        // TODO add your handling code here:
        
        if(nc==1){initCounter+=1;pc=0;nc=0;}
        System.err.println("Next Counter: "+initCounter);
        if(op1.isSelected())
            ansstr[initCounter-1] = op1.getText();
        else if(op2.isSelected())
            ansstr[initCounter-1] = op2.getText();
        else if(op3.isSelected())
            ansstr[initCounter-1] = op3.getText();
        else if(op4.isSelected())
            ansstr[initCounter-1] = op4.getText();
            

        if(initCounter > 0 && initCounter < 10){
            if(!ansstr[initCounter-1].equals(""))
                obj[initCounter-1].setBackground(Color.green); 
            else
                obj[initCounter-1].setBackground(Color.red); 
        }
        
        try {
            if(initCounter < 10){
            
            question.setText(ques[initCounter][0]);
            qnum.setText("Question No.: "+(initCounter+1));
            op1.setText(ques[initCounter][1]);
            op2.setText(ques[initCounter][2]);
            op3.setText(ques[initCounter][3]);
            op4.setText(ques[initCounter][4]);
            initCounter++;
        }
        } catch (Exception e) {
            System.err.println(e);
        }
        
        if(initCounter==10){
            submit.setEnabled(true);
            tc = tc + 1;
        }
        
        prevans.setText(ansstr[initCounter-1]);
        
        bgrp.clearSelection();  
        if(initCounter == 10){
            submit.setEnabled(true);
            nt.setEnabled(false);
        }
        ps.setEnabled(true);
    }//GEN-LAST:event_ntActionPerformed

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
        try {
            System.err.println("inicounter = "+initCounter);
        if(initCounter-1 == 0)
            ps.setEnabled(false);
        if(initCounter < 10)
            nt.setEnabled(true);
        if(pc==0){initCounter-=1;pc=1;nc=1;}
        prevans.setText(ansstr[initCounter-1]);
        if(op1.isSelected())
            ansstr[initCounter-1] = op1.getText();
        else if(op2.isSelected())
            ansstr[initCounter-1] = op2.getText();
        else if(op3.isSelected())
            ansstr[initCounter-1] = op3.getText();
        else if(op4.isSelected())
            ansstr[initCounter-1] = op4.getText();
        if(initCounter > 0 && initCounter < 10){
            if(!ansstr[initCounter-1].equals(""))
                obj[initCounter-1].setBackground(Color.green); 
            else
                obj[initCounter-1].setBackground(Color.red); 
        }
        try {
            if(initCounter >= 1){
            initCounter--;
            question.setText(ques[initCounter][0]);
            qnum.setText("Question No.: "+(initCounter+1));
            op1.setText(ques[initCounter][1]);
            op2.setText(ques[initCounter][2]);
            op3.setText(ques[initCounter][3]);
            op4.setText(ques[initCounter][4]);
        }
        } catch (Exception e) {
            System.err.println(e);
        }
        bgrp.clearSelection();
        } catch (Exception e) {
            ps.setEnabled(false);
            System.out.println(e);
        }
        nt.setEnabled(true);
    }//GEN-LAST:event_psActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(op1.isSelected())
            ansstr[9] = op1.getText();
        else if(op2.isSelected())
            ansstr[9] = op2.getText();
        else if(op3.isSelected())
            ansstr[9] = op3.getText();
        else if(op4.isSelected())
            ansstr[9] = op4.getText();
        int tmarks = 0;
        for(int i=0;i<10;i++){
            if(ansstr[i].equals(ques[i][5]))
                tmarks++;
        }
        tmarks = tmarks*5;
        String stat = tmarks>=25?"PASS":"FAIL";
        System.err.println("Total Marks: "+tmarks);
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ems","root","");
            Statement st=con.createStatement();
            ResultSet rs = st.executeQuery("select max, min from exam where eid='"+eid+"'");
            rs.next();
            String min = rs.getString("min"), max = rs.getString("max");
            st.executeUpdate("insert into result values('"+userid+"','"+eid+"',"+min+","+max+","+tmarks+",'"+stat+"','N')");
        } catch (Exception e) {
            System.err.println(e);
        }
        JOptionPane.showMessageDialog(question, "Submitted");
        this.dispose();

    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nt;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    private javax.swing.JTextField prevans;
    private javax.swing.JButton ps;
    private javax.swing.JButton q1;
    private javax.swing.JButton q10;
    private javax.swing.JButton q2;
    private javax.swing.JButton q3;
    private javax.swing.JButton q4;
    private javax.swing.JButton q5;
    private javax.swing.JButton q6;
    private javax.swing.JButton q7;
    private javax.swing.JButton q8;
    private javax.swing.JButton q9;
    private javax.swing.JLabel qnum;
    private javax.swing.JTextArea question;
    private javax.swing.JButton submit;
    private javax.swing.JLabel timers;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
