/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examination_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author majma
 */
public class RemoveExam extends javax.swing.JFrame {

    /**
     * Creates new form RemoveExam
     */
    public RemoveExam() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        etable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Examination");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etable.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        etable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Exam Name", "Maximum Marks", "Minimum Marks", "Exam Date", "Time in Minutes"
            }
        ));
        jScrollPane1.setViewportView(etable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 840, 260));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Exam ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 190, 30));

        eid.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        getContentPane().add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 300, 40));

        jButton1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/ems","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select count(*) from exam");
            rs.next();
            int rc = Integer.parseInt(rs.getString("count(*)"));
            DefaultTableModel dtm = (DefaultTableModel) etable.getModel();
            dtm.setRowCount(rc);
            etable.setModel(dtm);
            int counter = 0;
            rs = st.executeQuery("select * from exam");
            while(rs.next()){
                etable.setValueAt(rs.getString("eid"), counter, 0);
                etable.setValueAt(rs.getString("ename"), counter, 1);
                etable.setValueAt(rs.getString("max"), counter, 2);
                etable.setValueAt(rs.getString("min"), counter, 3);
                etable.setValueAt(rs.getString("date"), counter, 4);
                etable.setValueAt(rs.getString("time"), counter, 5);
                counter++;
            }
            
            con.close();
        } catch (Exception e) {
            System.err.println("DB Error");
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/ems","root","");
            Statement st = con.createStatement();
            st.executeUpdate("delete from exam where eid='"+eid.getText()+"'");
            JOptionPane.showMessageDialog(this, "Exam removed");
            ResultSet rs = st.executeQuery("select count(*) from exam");
            rs.next();
            int rc = Integer.parseInt(rs.getString("count(*)"));
            DefaultTableModel dtm = (DefaultTableModel) etable.getModel();
            dtm.setRowCount(rc);
            etable.setModel(dtm);
            int counter = 0;
            rs = st.executeQuery("select * from exam");
            while(rs.next()){
                etable.setValueAt(rs.getString("eid"), counter, 0);
                etable.setValueAt(rs.getString("ename"), counter, 1);
                etable.setValueAt(rs.getString("max"), counter, 2);
                etable.setValueAt(rs.getString("min"), counter, 3);
                etable.setValueAt(rs.getString("date"), counter, 4);
                etable.setValueAt(rs.getString("time"), counter, 5);
                counter++;
            }
            
            con.close();
        } catch (Exception e) {
            System.err.println("DB Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eid;
    private javax.swing.JTable etable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
